---
title: "Model 145: Comunicación de datos al pagador"
subtitle: "Model 145: Communication of data to the payer"
description: "This is an English translation of the Spanish 'Model 145' form."
author: "Translated by @mbojan."
date: "2022-04-07"
format: 
  html:
    toc: true
---

> Si prefiere no comunicar a la empresa o entidad pagadora alguno de los datos a que se refiere este modelo, la retención que se le practique podría resultar superior a la procedente. En tal caso, podrá recuperar la diferencia,
si procede, al presentar su declaración del IRPF correspondiente al ejercicio de que se trate.

If you prefer not to communicate any of the data referred to in this form to the paying company or entity, the withholding applied to you could be higher than the appropriate one. In such a case, you will be able to recover the difference, if applicable, when submitting your personal income tax return for the year in question.

> Atención: la inclusión de datos falsos, incompletos o inexactos en esta comunicación, así como la falta de comunicación de variaciones en los mismos que, de haber sido conocidas por el pagador, hubieran determinado una retención superior, constituye infracción tributaria sancionable con multa del 35 al 150 por 100 de las cantidades que se hubieran dejado de retener por esta causa. (Artículo 205 de la Ley 58/2003, de 17 de diciembre, General Tributaria).

Attention: the inclusion of false, incomplete or inaccurate data in this communication, as well as the lack of communication of variations in the same that, if known by the payer, would have determined a withholding higher, constitutes a tax offense punishable by a fine of 35 to 150 percent of the amounts that have not been withheld for this reason. (Article 205 of Law 58/2003, of December 17, General Tax).

# 1. Data of the recipient that makes the communication

> NIF

Put your NIE number here.

> Apellidos y Nombre

Last name and first name.

> Año de nacimiento

Year of birth.

> **Situación familiar**:

**Family situation**:

> - Soltero/a, viudo/a, divorciado/a o separado/a legalmente con hijos solteros menores de 18 años o incapacitados judicialmente y sometidos a patria potestad prorrogada o rehabilitada que conviven exclusivamente con Vd., sin convivir también con el otro progenitor, siempre que proceda consignar al menos un hijo o descendiente en el apartado 2 de este documento ............. `1`

Single, widowed, divorced or legally separated with single children under 18 years of age or legally incapacitated and subject to extended or rehabilitated parental authority who live exclusively with you, without also living with the other parent, provided that appropriate to record at least one child or descendant in section 2 of this document

> - Casado/a y no separado/a legalmente cuyo cónyuge no obtiene rentas superiores a 1.500 euros anuales, excluidas las exentas ....... `2`

Married and not legally separated whose spouse does not obtain income of more than 1,500 euros per year, excluding exempt income

> NIF del cónyuge (si ha marcado la casilla 2, deberá consignar en esta casilla el NIF de su cónyuge) ..............

Spouse's NIF (if you have checked box 2, you must enter your spouse's NIF in this box)

> - Situación familiar distinta de las dos anteriores (solteros sin hijos, casados cuyo cónyuge obtiene rentas superiores a 1.500 euros anuales, ..., etc.) .............. `3`  
> (Marque también esta casilla si no desea manifestar su situación familiar).

Family situation other than the two above (single without children, married whose spouse earns more than 1,500 euros per year, ..., etc.)  
(Please also check this box if you do not wish to disclose your family situation.)

> **Discapacidad** (grado de discapacidad reconocido):

Disability (recognized degree of disability):

> Igual o superior al 33% e inferior al 65% .....

Equal to or greater than 33% and less than 65%

> Igual o superior al 65% .....

Equal to or greater than 65%

> Además, tengo acreditada la necesidad de ayuda de terceras personas o movilidad reducida 

In addition, I have proven the need for help from third parties or reduced mobility

> **Movilidad geográfica**:

> Si anteriormente estaba Vd. en situación de desempleo e inscrito en la oficina de empleo y la aceptación del puesto de trabajo actual ha exigido el traslado de su residencia habitual a un nuevo municipio, indique la fecha de dicho traslado .............................................................................

If you were previously unemployed and registered at the employment office and the acceptance of the current job has required the transfer of your habitual residence to a new municipality, indicate the date of said transfer.

> Obtención de rendimientos con período de generación superior a 2 años durante los 5 períodos impositivos anteriores:

Obtaining income with a generation period of more than 2 years during the 5 previous tax periods.

> Marque esta casilla si, en el plazo comprendido en los 5 períodos impositivos anteriores al ejercicio al que corresponde la presente comunicación, ha percibido rendimientos del trabajo con período de generación superior a 2 años, a los que, a efectos del cálculo del tipo de retención le haya sido aplicada la reducción por irregularidad contemplada en el artículo 18.2 de la Ley del Impuesto y, sin embargo, posteriormente usted no haya aplicado la citada reducción en su correspondiente autoliquidación del Impuesto sobre la Renta .......

Check this box if, in the period included in the 5 tax periods prior to the year to which this communication corresponds, you have received income from work with a generation period of more than 2 years, to which, for the purposes of calculating the withholding rate The reduction for irregularity contemplated in article 18.2 of the Tax Law has been applied to you and, however, subsequently you have not applied the aforementioned reduction in your corresponding Income Tax self-assessment




# 2. Hijos y otros descendientes menores de 25 años, o mayores de dicha edad si son discapacitados, que conviven con el perceptor

> Datos de los hijos o descendientes menores de 25 años (o mayores de dicha edad si son discapacitados) que conviven con Vd. y que no tienen rentas anuales superiores a 8.000 euros.

*This is a table with the following columns and sub-columns:*

1. Año de nacimiento
2. Año de adopción o acogimiento [^1]
3. **Hijos o descendientes con discapacidad** (grado de discapacidad reconocido)  
   Si alguno de los hijos o descendientes tiene reconocido un grado de discapacidad igual o superior al 33 por 100, marque con una "X" la/s casilla/s que corresponda/n a su situación.
    - Grado igual o superior al 33% e inferior al 65%
    - Grado igual o superior al 65%
    - Además, tiene acreditada la necesidad de ayuda de terceras personas o movilidad reducida
4. **Cómputo por entero de hijos o descendientes**  
   En caso de hijos que convivan únicamente con Vd., sin convivir también con el otro progenitor (padre o madre), o de nietos que convivan únicamente con Vd., sin convivir también con ningún otro de sus abuelos, indíquelo marcando con una "X" esta casilla.

**Atención**: Si tiene más de cuatro hijos o descendientes, adjunte otro ejemplar con los datos del quinto y sucesivos.

[^1]: Solamente en el caso de hijos adoptados o de menores acogidos. Tratándose de hijos adoptados que previamente hubieran estado acogidos, indique únicamente el año del acogimiento.


# 3. Ascendientes mayores de 65 años, o menores de dicha edad si son discapacitados, que conviven con el perceptor

> Datos de los ascendientes mayores de 65 años (o menores de dicha edad si son discapacitados) que conviven con Vd. durante, al menos, la mitad del año y que no tienen rentas anuales superiores a 8.000 euros.

*This is a table with the following columns and sub-columns:*

1. Año de nacimiento
2. Ascendientes con discapacidad (grado de discapacidad reconocido)  
   Si alguno de los ascendientes tiene reconocido un grado de discapacidad igual o superior al 33 por 100, marque con una "X" la/s casilla/s que corresponda/n a su situación.
    - Grado igual o superior al 33% e inferior al 65%
    - Grado igual o superior al 65%
    - Además, tiene acreditada la necesidad de ayuda de terceras personas o movilidad reducida
3. Convivencia con otros descendientes  
   Si alguno de los ascendientes convive también, al menos durante la mitad del año, con otros descendientes del mis- mo grado que Vd., indique en esta casilla el número total de descendientes con los que convive, incluido Vd. (Si los ascendientes sólo conviven con Vd., no rellene esta casilla).


# 4. Pensiones compensatorias en favor del cónyuge y anualidades por alimentos en favor de los hijos, fijadas ambas por decisión judicial

**Pensión compensatoria en favor del cónyuge.** Importe anual que está Vd. obligado a satisfacer por resolución judicial 

**Anualidades por alimentos en favor de los hijos.** Importe anual que está Vd. obligado a satisfacer por resolución judicial

# 5. Pagos por la adquisición o rehabilitación de la vivienda habitual utilizando financiación ajena, con derecho a deducción en el IRPF

**Importante:** sólo podrán cumplimentar este apartado los contribuyentes que hayan adquirido su vivienda habitual, o hayan satisfecho cantidades por obras de rehabilitación de la misma, antes del 1 de enero de 2013.

Si está Vd. efectuando pagos por préstamos destinados a la adquisición o rehabilitación de su vivienda habitual por los que vaya a tener derecho a deducción por inversión en vivienda habitual en el IRPF y la cuantía total de sus retribuciones íntegras en concepto de rendimientos del trabajo procedentes de todos sus pagadores es inferior a 33.007,20 euros anuales, marque con una "X" esta casilla

# 6. Fecha y firma de la comunicación

Manifiesto ser contribuyente del IRPF y declaro que son ciertos los datos arriba indicados, presentando ante la empresa o entidad pagadora la presente comunicación de mi situación personal y familiar, o de su variación, a los efectos previstos en el artículo 88 del Reglamento del IRPF.

# 7. Acuse de recibo

La empresa o entidad:

acusa recibo de la presente comunicación y documentación.

---

> De conformidad con lo dispuesto en el artículo 11 de la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales, el perceptor tendrá derecho a ser informado previamente de la existencia de un fichero o tratamiento de datos de carácter personal, de la finalidad de la recogida de éstos y de los destinatarios de la información, de la identidad y dirección del responsable del tratamiento o, en su caso, de su representante, así como de la posibilidad de ejercitar sus derechos de acceso, rectificación o cancelación de los mismos.
